name: Upload and Post-Processing

on:
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'Device Name'
        required: true
      FILE_DATE:
        description: 'File Date'
        required: true
      FIRMWARE_PATH:
        description: 'Firmware Path'
        required: true

jobs:
  upload-and-post:
    runs-on: ubuntu-latest

    steps:
    - name: Upload firmware directory
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_firmware_${{ github.event.inputs.DEVICE_NAME }}_${{ github.event.inputs.FILE_DATE }}
        path: ${{ github.event.inputs.FIRMWARE_PATH }}

    - name: Generate release tag and upload
      uses: softprops/action-gh-release@v1
      with:
        tag_name: $(date +"%Y.%m.%d")-${{ github.event.inputs.DEVICE_NAME }}
        files: ${{ github.event.inputs.FIRMWARE_PATH }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.3
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
